//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoWeb2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.CARRITOes = new HashSet<CARRITO>();
            this.VENTAs = new HashSet<VENTA>();
        }
    
        public int IdCliente { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public Nullable<bool> Restablecer { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual ICollection<CARRITO> CARRITOes { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<VENTA> VENTAs { get; set; }
    }
}
