//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoWeb2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCARRITOEntities : DbContext
    {
        public DBCARRITOEntities()
            : base("name=DBCARRITOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CARRITO> CARRITO { get; set; }
        public DbSet<CATEGORIA> CATEGORIA { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public DbSet<DISTRITO> DISTRITO { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<UBICACION> UBICACION { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VENTA> VENTA { get; set; }
    }
}
