//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoWeb2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBCARRITOEntities : DbContext
    {
        public DBCARRITOEntities()
            : base("name=DBCARRITOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public DbSet<CLIENTE> CLIENTEs { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTOes { get; set; }
        public DbSet<DETALLE_VENTA> DETALLE_VENTA { get; set; }
        public DbSet<DISTRITO> DISTRITOes { get; set; }
        public DbSet<PROVINCIA> PROVINCIAs { get; set; }
        public DbSet<UBICACION> UBICACIONs { get; set; }
        public DbSet<USUARIO> USUARIOs { get; set; }
        public DbSet<VENTA> VENTAs { get; set; }
        public DbSet<CARRITO> CARRITOes { get; set; }
        public DbSet<PRODUCTO> PRODUCTOes { get; set; }
    }
}
